name: macromeals
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - catalogue=2.0.10
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - comm=0.2.2
  - confection=0.1.4
  - cymem=2.0.6
  - cython-blis=0.7.11
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - idna=3.4
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - langcodes=3.3.0
  - libcxx=16.0.6
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - murmurhash=1.0.7
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.2.1
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.0
  - preshed=3.0.6
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - rich=13.3.5
  - setuptools=69.2.0
  - shellingham=1.5.0
  - six=1.16.0
  - smart_open=5.2.1
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - srsly=2.4.8
  - stack_data=0.6.2
  - thinc=8.2.2
  - tk=8.6.13
  - tornado=6.4
  - tqdm=4.65.0
  - traitlets=5.14.2
  - typer=0.9.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wasabi=0.9.1
  - wcwidth=0.2.13
  - weasel=0.3.4
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - pip:
      - blinker==1.7.0
      - en-core-web-md==3.7.1
      - flask==3.0.3
      - flask-cors==4.0.0
      - flask-sqlalchemy==3.1.1
      - fuzzywuzzy==0.18.0
      - greenlet==3.0.3
      - itsdangerous==2.2.0
      - jellyfish==1.0.3
      - levenshtein==0.25.1
      - myfitnesspal==1.0
      - pymysql==1.1.0
      - python-levenshtein==0.25.1
      - rapidfuzz==3.8.1
      - sqlalchemy==2.0.29
      - websockets==12.0
      - werkzeug==3.0.2
      - zipp==3.15.0
